name: Package Repository

on:
  push:
    branches:
      - main
    paths:
      - '_repos/**'
      - 'resources/**'
      - 'localization/**'
      - '.gitmodules'
      - '.github/workflows/package.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get current time
      run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

    - name: Checkout repository
      uses: actions/checkout@v4.1.5
      with:
        submodules: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Per-mod re-arranging
      run: |
        echo "Start re-arranging mod files..."

        mv mod_loc/Cartomancer/* _repos/Cartomancer/localization/
        rm -rf mod_loc

        mv _repos Mods
        mv custom_misc/* Mods
        mv no_repo/* Mods
        cd Mods

        rm -rf Betmma/5_legendary_challenges

        mv BonusBlinds/BonusBlinds/* BonusBlinds/

        mv CheesyJokers/CheesyJokers 098_CheesyJokers
        rm -rf CheesyJokers

        mv CodexArcanum/mod 098_Codex_Arcanum
        rm -rf CodexArcanum

        mv 098_FusionJokers/mod .
        rm -rf 098_FusionJokers
        mv mod 098_FusionJokers

        mv CruelBlinds/CruelBlinds_1_0_0 .
        rm -rf CruelBlinds
        mv CruelBlinds_1_0_0 CruelBlinds

        mkdir je_t
        mv JokerEvolution/JokerEvolution/* je_t
        rm -rf JokerEvolution
        mv je_t JokerEvolution

        rm -rf KCVanilla/scripts

        mv "SDM0/SDM_0's Stuff" "SDM_0's Stuff"
        rm -rf SDM0

        rm -rf Steamodded/example_mods

        rm -rf 098_Jestobiology/img

        mv MikasBalatro 098_MikasBalatro

        mv Myst/Steamodded/MystJokers 098_MystJokers
        rm -rf Myst

        curl -L https://raw.githubusercontent.com/happinyz/BalatroFoldButton/main/FoldButton.lua -o .

    - name: Universal unwanted files/directories removal
      run: |
        echo "Start deleting redundant files..."
        rm -rf .git .gitmodules git-assets
        pushd ./Mods
        find . -maxdepth 2 -type f -iname '*.py' -exec rm -f {} +
        find . -maxdepth 2 -type f -iname 'icon.png' -exec rm -f {} +
        find . -maxdepth 2 -type f -iname 'm6x11plus.ttf' -exec rm -f {} +
        find . -maxdepth 2 -type f -iname 'manifest.json' -exec rm -f {} +
        popd
        find . -type f -iname 'LICENSE' -exec rm -f {} +
        find . -type f -iname 'TODO' -exec rm -f {} +
        find . -type f -iname '*.md' -exec rm -f {} +
        find . -type f -iname '*.fish' -exec rm -f {} +
        find . -type f -iname '*.asc' -exec rm -f {} +
        find . -type f -iname '*.html' -exec rm -f {} +
        find . -type f -iname '*.js' -exec rm -f {} +
        find . -type f -iname '*.css' -exec rm -f {} +
        find . -type f -iname '.git' -exec rm -f {} +
        find . -type f -iname '.luarc.json' -exec rm -f {} +
        find . -type f -iname '.gitignore' -exec rm -f {} +
        find . -type f -iname '.gitattributes' -exec rm -f {} +
        find . -type d -name 'site' -exec rm -rf {} +
        find . -type d -iname '.vscode' -exec rm -rf {} +
        find . -type d -iname '.github' -exec rm -rf {} +
        find . -type d -name 'gitresources' -exec rm -rf {} +

    - name: Construct artifacts
      run: |
        mkdir mobile && rsync -av --exclude='mobile' . mobile/
        mkdir standard && rsync -av --exclude='standard' --exclude='mobile' . standard/

        cd ./mobile/Mods
        mv mobile_patches/mobile-patch ./
        rsync -av mobile_patches/patched-shaders/* ./
        rm -rf mobile_patches

    - name: Upload standard artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: pack-stan-snapshot-${{ env.TIMESTAMP }}
        path: ./standard/

    - name: Upload mobile artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: pack-mobile-snapshot-${{ env.TIMESTAMP }}
        path: ./mobile/
