name: Package Repository

on:
  push:
    branches:
      - overlord
    paths:
      - 'Mods/**'
      - 'resources/**'
      - 'localization/**'
      - '.github/workflows/package.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.5
      with:
        submodules: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Per-mod files/directories clean-up
      run: |
        echo "Start re-arranging mod files..."

    - name: Universal unwanted files/directories removal
      run: |
        echo "Start deleting redundant files..."

        rm -rf .gitignore .gitmodules .github
        find ./Mods -maxdepth 2 -type f -name 'icon.png' -exec rm -f {} +
        find ./Mods -maxdepth 2 -type f -name 'index.html' -exec rm -f {} +
        find ./Mods -maxdepth 2 -type f -name 'm6x11plus.ttf' -exec rm -f {} +
        find . -type d -name '.git' -exec rm -rf {} +
        find . -type d -name 'site' -exec rm -rf {} +
        find . -type d -name '.github' -exec rm -rf {} +
        find . -type d -name '.vscode' -exec rm -rf {} +
        find . -type d -name 'gitresources' -exec rm -rf {} +
        find . -type f -name '*.py' -exec rm -f {} +
        find . -type f -name '*.sh' -exec rm -f {} +
        find . -type f -name '*.bat' -exec rm -f {} +
        find . -type f -name '*.ps1' -exec rm -f {} +
        find . -type f -name '.git' -exec rm -rf {} +
        find . -type f -iname 'LICENSE' -exec rm -f {} +
        find . -type f -iname 'style.css' -exec rm -f {} +
        find . -type f -iname 'README.md' -exec rm -f {} +
        find . -type f -iname 'README.asc' -exec rm -f {} +
        find . -type f -name '.gitignore' -exec rm -rf {} +
        find . -type f -iname 'changelog.md' -exec rm -f {} +
        find . -type f -iname 'addjokers.js' -exec rm -f {} +
        find . -type f -iname 'CHANGELOG.md' -exec rm -f {} +
        find . -type f -iname 'manifest.json' -exec rm -f {} +
        find . -type f -name '.gitattributes' -exec rm -rf {} +
        find . -type f -iname 'generate_sprite.fish' -exec rm -f {} +

    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: pack_snapshot
        path: ./
